export const dataCountry = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antigua & Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bosnia & Herzegovina",
	"Botswana",
	"Brazil",
	"British Virgin Islands",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Cape Verde",
	"Cayman Islands",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Congo",
	"Cook Islands",
	"Costa Rica",
	"Cote D'Ivoire",
	"Croatia",
	"Cruise Ship",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Estonia",
	"Ethiopia",
	"Falkland Islands",
	"Faroe Islands",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French West Indies",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kuwait",
	"Kyrgyz Republic",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Martinique",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Namibia",
	"Nepal",
	"Netherlands",
	"Netherlands Antilles",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norway",
	"Oman",
	"Pakistan",
	"Palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Reunion",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Pierre & Miquelon",
	"Samoa",
	"San Marino",
	"Satellite",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"South Africa",
	"South Korea",
	"Spain",
	"Sri Lanka",
	"St Kitts & Nevis",
	"St Lucia",
	"St Vincent",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor L'Este",
	"Togo",
	"Tonga",
	"Trinidad & Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks & Caicos",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"Uruguay",
	"Uzbekistan",
	"Venezuela",
	"Vietnam",
	"Virgin Islands (US)",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];

export const dataLanguage = [
	"Afrikaans",
	"Albanian - shqip",
	"Amharic - አማርኛ",
	"Arabic - العربية",
	"Aragonese - aragonés",
	"Armenian - հայերեն",
	"Asturian - asturianu",
	"Azerbaijani - azərbaycan dili",
	"Basque - euskara",
	"Belarusian - беларуская",
	"Bengali - বাংলা",
	"Bosnian - bosanski",
	"Breton - brezhoneg",
	"Bulgarian - български",
	"Catalan - català",
	"Central Kurdish - کوردی (دەستنوسی عەرەبی)",
	"Chinese - 中文",
	"Chinese (Hong Kong) - 中文（香港）",
	"Chinese (Simplified) - 中文（简体）",
	"Chinese (Traditional) - 中文（繁體）",
	"Corsican",
	"Croatian - hrvatski",
	"Czech - čeština",
	"Danish - dansk",
	"Dutch - Nederlands",
	"English",
	"English (Australia)",
	"English (Canada)",
	"English (India)",
	"English (New Zealand)",
	"English (South Africa)",
	"English (United Kingdom)",
	"English (United States)",
	"Esperanto - esperanto",
	"Estonian - eesti",
	"Faroese - føroyskt",
	"Filipino",
	"Finnish - suomi",
	"French - français",
	"French (Canada) - français (Canada)",
	"French (France) - français (France)",
	"French (Switzerland) - français (Suisse)",
	"Galician - galego",
	"Georgian - ქართული",
	"German - Deutsch",
	"German (Austria) - Deutsch (Österreich)",
	"German (Germany) - Deutsch (Deutschland)",
	"German (Liechtenstein) - Deutsch (Liechtenstein)",
	"German (Switzerland) - Deutsch (Schweiz)",
	"Greek - Ελληνικά",
	"Guarani",
	"Gujarati - ગુજરાતી",
	"Hausa",
	"Hawaiian - ʻŌlelo Hawaiʻi",
	"Hebrew - עברית",
	"Hindi - हिन्दी",
	"Hungarian - magyar",
	"Icelandic - íslenska",
	"Indonesian - Indonesia",
	"Interlingua",
	"Irish - Gaeilge",
	"Italian - italiano",
	"Italian (Italy) - italiano (Italia)",
	"Italian (Switzerland) - italiano (Svizzera)",
	"Japanese - 日本語",
	"Kannada - ಕನ್ನಡ",
	"Kazakh - қазақ тілі",
	"Khmer - ខ្មែរ",
	"Korean - 한국어",
	"Kurdish - Kurdî",
	"Kyrgyz - кыргызча",
	"Lao - ລາວ",
	"Latin",
	"Latvian - latviešu",
	"Lingala - lingála",
	"Lithuanian - lietuvių",
	"Macedonian - македонски",
	"Malay - Bahasa Melayu",
	"Malayalam - മലയാളം",
	"Maltese - Malti",
	"Marathi - मराठी",
	"Mongolian - монгол",
	"Nepali - नेपाली",
	"Norwegian - norsk",
	"Norwegian Bokmål - norsk bokmål",
	"Norwegian Nynorsk - nynorsk",
	"Occitan",
	"Oriya - ଓଡ଼ିଆ",
	"Oromo - Oromoo",
	"Pashto - پښتو",
	"Persian - فارسی",
	"Polish - polski",
	"Portuguese - português",
	"Portuguese (Brazil) - português (Brasil)",
	"Portuguese (Portugal) - português (Portugal)",
	"Punjabi - ਪੰਜਾਬੀ",
	"Quechua",
	"Romanian - română",
	"Romanian (Moldova) - română (Moldova)",
	"Romansh - rumantsch",
	"Russian - русский",
	"Scottish Gaelic",
	"Serbian - српски",
	"Serbo - Croatian",
	"Shona - chiShona",
	"Sindhi",
	"Sinhala - සිංහල",
	"Slovak - slovenčina",
	"Slovenian - slovenščina",
	"Somali - Soomaali",
	"Southern Sotho",
	"Spanish - español",
	"Spanish (Argentina) - español (Argentina)",
	"Spanish (Latin America) - español (Latinoamérica)",
	"Spanish (Mexico) - español (México)",
	"Spanish (Spain) - español (España)",
	"Spanish (United States) - español (Estados Unidos)",
	"Sundanese",
	"Swahili - Kiswahili",
	"Swedish - svenska",
	"Tajik - тоҷикӣ",
	"Tamil - தமிழ்",
	"Tatar",
	"Telugu - తెలుగు",
	"Thai - ไทย",
	"Tigrinya - ትግርኛ",
	"Tongan - lea fakatonga",
	"Turkish - Türkçe",
	"Turkmen",
	"Twi",
	"Ukrainian - українська",
	"Urdu - اردو",
	"Uyghur",
	"Uzbek - o‘zbek",
	"Vietnamese - Tiếng Việt",
	"Walloon - wa",
	"Welsh - Cymraeg",
	"Western Frisian",
	"Xhosa",
	"Yiddish",
	"Yoruba - Èdè Yorùbá",
	"Zulu - isiZulu",
];

export const dataProgrammingLanguage = [
	"Python",
	"C",
	"C++",
	"Java",
	"C#",
	".Net",
	"Javascript",
	"Typescript",
	"SQL",
	"Assembly language",
	"PHP",
	"R",
	"Go",
	"Swift",
	"Pascal",
	"Ruby",
	"Perl",
	"Objective-C",
	"Rust",
	"Scratch",
	"Kotlin",
	"Julia",
	"Lua",
	"Fortran",
	"COBOL",
	"Dart",
	"Scala",
	"Bash",
	"Powershell",
];

export const dataPost = [
	"CEO",
	"CTO",
	"SEO Specialist",
	"Product Manager",
	"Software Architect",
	"Fullstack Developer",
	"Application Engineer",
	"Programmer",
	"Administrator",
	"Chief Technology Officer",
	"DevOps Engineer",
	"Frontend Developer",
	"Chief Architect",
	"Systems analyst",
	"Mobile Developer",
	"Database Administrator",
	"Web designer",
	"Software Engenieer",
	"Backend Developer",
	"Project Manager",
	"Data Scientist",
	"Data Analyst",
	"Data Engineer",
	"Data Architect",
	"IT Consultant",
	"Freelancer",
	"UI/UX Designer",
	"Graphic Designer",
	"Game Developer",
	"Game Designer",
	"3D Artist",
];